heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: centos
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: m1.tiny.vnf
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    default: my_key
  traffic_network_name:
    type: string
    label: Traffic network name or ID
    description: Network to attach instance to.
    default: traffic_network_0
  mgmt_network_name:
    type: string
    label: Management network name or ID
    description: Network to attach instance to.
    default: mgmt_net
  traffic_network_cidr:
    type: string
    default: 192.168.0.0/24

resources:
  vnf_network:
    type: Lib::VNF::Network
    properties:
      traffic_network_name: { get_param: traffic_network_name }
      traffic_network_cidr: { get_param: traffic_network_cidr }
  svrgrp: 
    type: OS::Nova::ServerGroup 
    properties: 
      name: svrgrp 
      policies: [ 'anti-affinity' ] 

  vnfc_1:
    type: Lib::VNF::Vnfc
    properties:
      key: { get_param: key }
      flavor: { get_param: flavor }
      image: { get_param: image }
      mgmt_network_name: { get_param: mgmt_network_name }
      traffic_network_name: { get_attr: [vnf_network, traffic_network] }
      server_group: { get_resource: svrgrp }

  vnfc_2:
    type: Lib::VNF::Vnfc
    properties:
      key: { get_param: key }
      flavor: { get_param: flavor }
      image: { get_param: image }
      mgmt_network_name: { get_param: mgmt_network_name }
      traffic_network_name: { get_attr: [vnf_network, traffic_network] }
      server_group: { get_resource: svrgrp } 
