heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: centos
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: m1.tiny.vnf
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    default: my_key
  traffic_network_name:
    type: string
    label: Traffic network name or ID
    description: Network to attach instance to.
    default: traffic_network_0
  mgmt_network_name:
    type: string
    label: Management network name or ID
    description: Network to attach instance to.
    default: mgmt_net
  traffic_network_cidr:
    type: string
    default: 192.168.0.0/24

resources:
  traffic_network:
    type: OS::Neutron::Net
    properties:
      name: { get_param: traffic_network_name }
  traffic_network_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: traffic_network }
      cidr: { get_param: traffic_network_cidr }
  svrgrp: 
    type: OS::Nova::ServerGroup 
    properties: 
      name: svrgrp 
      policies: [ 'anti-affinity' ] 
  vnfc-1:
    type: OS::Nova::Server
    depends_on: [traffic_network_subnet]
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - network: { get_param: mgmt_network_name }
        - network: { get_resource: traffic_network }
      scheduler_hints: { group: { get_resource: svrgrp } }
  vnfc-2:
    type: OS::Nova::Server
    depends_on: [traffic_network_subnet]
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - network: { get_param: mgmt_network_name }
        - network: { get_resource: traffic_network }
      scheduler_hints: { group: { get_resource: svrgrp } }
