heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
  mgmt_network_name:
    type: string
    label: Management network name or ID
  ext_network_name:
    type: string
    label: Management network name or ID

resources:
  vnfm:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - port: { get_resource: mgmt_port }

  mgmt_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_parameter: mgmt_network_name }

  mgmt_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: mgmt_port }
